### ISSUE TITLE
Officially maintained OWASP ZAP Node API

### ISSUE THREAD

**Issue by binarymist** [sbilly/awesome-security#106]
This API has been unmaintained for several years, I'm the new owner and keeping it maintained now

* [The API code](https://github.com/zaproxy/zap-api-nodejs)
* [Now official](https://github.com/zaproxy/zaproxy/wiki/ApiDetails)
* [Official announcement](https://twitter.com/zaproxy/status/1063378335928131585)
* [Main issue](https://github.com/zaproxy/zaproxy/issues/5044)
* [Main PR](https://github.com/zaproxy/zap-api-nodejs/pull/1)
* [What's changed](https://github.com/zaproxy/zap-api-nodejs/blob/master/CHANGELOG.md)

Interested in a PR?

**Comment by sbilly** [comment]
send pr please.
