### ISSUE TITLE
Add "hardened_malloc" (Hardened allocator) to "Mobile / Android / iOS" category

### ISSUE THREAD

**Issue by beerisgood** [sbilly/awesome-security#147]
Under https://github.com/sbilly/awesome-security#mobile--android--ios adding project "hardened_malloc" would be nice.

> Hardened allocator designed for modern systems. It has integration into Android's Bionic libc and can be used externally with musl and glibc as a dynamic library for use on other Linux-based platforms. It will gain more portability / integration over time.

https://github.com/GrapheneOS/hardened_malloc

**Comment by sbilly** [comment]
Please send a pull request.

**Comment by beerisgood** [comment]
@sbilly done: https://github.com/sbilly/awesome-security/pull/148

**Comment by sbilly** [comment]
merged
