### ISSUE TITLE
adding tools from awesome-sysadmin, which category?

### ISSUE THREAD

**Issue by n1trux** [sbilly/awesome-security#28]
Hi,

I just noticed this list and linked to it [from my awesome-sysadmin repo](https://github.com/n1trux/awesome-sysadmin).

There were some duplicates, but my list had some tools which are not already on here. I'm not sure where to sort them though – here's the list, in italics behind the entries are my suggestions on where to sort it.

Please tell me where these tools belong (or if they're not awesome enough) and I come up with a short description and create a PR.

>
  * [Blackbox](https://github.com/StackExchange/blackbox) - Safely store secrets in Git/Mercurial. Provides tooling to automatically encrypt secrets like passwords. ***DevOps?***
  * [Denyhosts](http://denyhosts.sourceforge.net/) - Thwart SSH dictionary based attacks and brute force attacks. ***IPS***
  * [Fail2Ban](http://www.fail2ban.org/wiki/index.php/Main_Page) - Scans log files and takes action on IPs that show malicious behavior. ***IPS***
  * [FIR](https://github.com/certsocietegenerale/FIR) - Fast Incident Response, a cybersecurity incident management platform.  ***SIEM***
  * [fwknop](https://www.cipherdyne.org/fwknop/) - Protects ports via Single Packet Authorization in your firewall.  ***IPS/Firewall?***
  * [Linux Malware Detect](https://www.rfxn.com/projects/linux-malware-detect/) - A malware scanner for Linux designed around the threats faced in shared hosted environments. ***Scanner***
  * [Nmap](https://nmap.org) - Nmap is a free and open source utility for network discovery and security auditing. ***Scanner***
  * [OSQuery](https://osquery.io/) - Query your servers status and info using a SQL like interface. ***DevOps?***
  * [pfSense](https://www.pfsense.org/) - Firewall and Router FreeBSD distribution.  ***IPS/Firewall?***
  * [SpamAssassin](https://spamassassin.apache.org/) - A powerful and popular email spam filter employing a variety of detection technique. ***not sure***
  * [SSHGuard](http://www.sshguard.net/) - A software to protect services in addition to SSH, written in C ***IPS***

I suggest to add a new category "Firewall" to distinguish that from IDS/IPS.

**Comment by Bifrozt** [comment]
+1

**Comment by n1trux** [comment]
@Bifrozt: you can directly react to an issue or PR by clicking the "smiley" reaction button ("+☺") on the top right of the entry (in the line "… commented … ago" on the far right).

**Comment by Bifrozt** [comment]
@n1trux thnx for the tip but, that didn't work too well from my cellphone apparently

**Comment by sbilly** [comment]
>   * [Blackbox](https://github.com/StackExchange/blackbox) - Safely store secrets in Git/Mercurial. Provides tooling to automatically encrypt secrets like passwords. ***DevOps?***
You can add a New TOP level category, 'SDL'

>  * [Denyhosts](http://denyhosts.sourceforge.net/) - Thwart SSH dictionary based attacks and brute force attacks. ***IPS***
YES, add to 'IDS / IPS / Host IDS / Host IPS'

>  * [Fail2Ban](http://www.fail2ban.org/wiki/index.php/Main_Page) - Scans log files and takes action on IPs that show malicious behavior. ***IPS***
YES, add to 'IDS / IPS / Host IDS / Host IPS'

>   * [FIR](https://github.com/certsocietegenerale/FIR) - Fast Incident Response, a cybersecurity incident management platform.  ***SIEM***
YES, add to 'Security Information & Event Management'

>  * [fwknop](https://www.cipherdyne.org/fwknop/) - Protects ports via Single Packet Authorization in your firewall.  ***IPS/Firewall?***
It's a kind of backdoor for administrator. I think It's not good for security.

>  * [Linux Malware Detect](https://www.rfxn.com/projects/linux-malware-detect/) - A malware scanner for Linux designed around the threats faced in shared hosted environments. ***Scanner***
YES, you can add to 'Endpoint' - 'Anti-Virus / Anti-Maleware .'

>  * [Nmap](https://nmap.org) - Nmap is a free and open source utility for network discovery and security auditing. ***Scanner***
Yes, you can add to 'Scanning / Pentesting'

>  * [OSQuery](https://osquery.io/) - Query your servers status and info using a SQL like interface. ***DevOps?***
I think it's not a security tools, but U can add to 'Forensics'

>  * [pfSense](https://www.pfsense.org/) - Firewall and Router FreeBSD distribution.  ***IPS/Firewall?***
You can add it to 'Network' - 'Firewall'

>  * [SpamAssassin](https://spamassassin.apache.org/) - A powerful and popular email spam filter employing a variety of detection technique. ***not sure***
You can add it to 'Network' - 'Anti-Spam'

>  * [SSHGuard](http://www.sshguard.net/) - A software to protect services in addition to SSH, written in C ***IPS***
YES, add to 'IDS / IPS / Host IDS / Host IPS'

**Comment by n1trux** [comment]
@sbilly should I do it all in one PR (separate commits for each program) or separate PRs?

**Comment by sbilly** [comment]
all in one is ok.
