### ISSUE TITLE
Stealth

### ISSUE THREAD

**Issue by binarymist** [sbilly/awesome-security#41]
Just wondering where stealth is on the list of HIDS?

I've had very good success with it, and have tried a bunch of HIDS and [evaluated them](https://leanpub.com/holistic-infosec-for-web-developers-fascicle1-vps-network-cloud-webapplications/read#vps-countermeasures-lack-of-visibility-host-intrusion-detection-systems-hids) based on use within my networks.

**Comment by sbilly** [comment]
You can add them to [Host IDS section](https://github.com/sbilly/awesome-security#ids--ips--host-ids--host-ips) and send a PR.

**Comment by binarymist** [comment]
PR #45

**Comment by sbilly** [comment]
done.
