### ISSUE TITLE
Honeypots extravoganza

### ISSUE THREAD

**Issue by binarymist** [sbilly/awesome-security#42]
Is it worth including the [canonicle list](https://github.com/paralax/awesome-honeypots) in your [list](https://github.com/sbilly/awesome-security#honey-pot--honey-net)? Seems like it would make sense.

**Comment by sbilly** [comment]
You can send a PR. Thank you.

**Comment by binarymist** [comment]
#46

**Comment by sbilly** [comment]
done.
