### ISSUE TITLE
OWASP NodeGoat Docker Image

### ISSUE THREAD

**Issue by binarymist** [sbilly/awesome-security#43]
https://github.com/owasp/nodegoat has a [docker image](https://github.com/owasp/nodegoat#option-3---run-nodegoat-on-docker) which I've done quite a bit of work on and works well, may be worth adding. Let me know if you would rather have a PR?

Here is the [wiki](https://github.com/binarymist/NodeGoat/wiki/Security-Regression-Testing-with-Zap-API) around security regression testing for NodeGoat <-> ZAP that has a video teaser also.

**Comment by sbilly** [comment]
send PR please. you can add a new section on [Web](https://github.com/sbilly/awesome-security#web)

**Comment by binarymist** [comment]
Not under https://github.com/sbilly/awesome-security#docker-images-for-penetration-testing--security ?

**Comment by sbilly** [comment]
you can add it to the docker image list. I'll do some clean & reclassification in few weeks.
