### ISSUE TITLE
New section around VPS?

### ISSUE THREAD

**Issue by binarymist** [sbilly/awesome-security#44]
I'd love to see and be able to contribute to a [VPS section](https://leanpub.com/holistic-infosec-for-web-developers-fascicle1-vps-network-cloud-webapplications/read#vps). Items like OSSEC are really [Host IDS](https://leanpub.com/holistic-infosec-for-web-developers-fascicle1-vps-network-cloud-webapplications/read#vps-countermeasures-lack-of-visibility-host-intrusion-detection-systems-hids) rather than [Network IDS](https://leanpub.com/holistic-infosec-for-web-developers-fascicle1-vps-network-cloud-webapplications/read#leanpub-auto-network-intrusion-detection-systems-nids). There are also [other offerings](https://leanpub.com/holistic-infosec-for-web-developers-fascicle1-vps-network-cloud-webapplications/read#web-applications-countermeasures-consuming-free-and-open-source-tooling) very similar to Snyk that are free and open source.

Source for my books:
https://github.com/binarymist/HolisticInfoSec-For-WebDevelopers-Fascicle0
https://github.com/binarymist/HolisticInfoSec-For-WebDevelopers-Fascicle1

**Comment by binarymist** [comment]
Let me know if you'd be keen and I'll sub a PR for all / some of these issues?

**Comment by sbilly** [comment]
VPS is Virtual Private Server or something eles ? What's the difference between VPS and Host IDS / Network IDS?

You can send PR. I'm more likely to add to current section.

**Comment by binarymist** [comment]
Re: VPS, yeah. It's just that many items apply more specifically to VPS/host/machine, than network, which usually has many VPS/host/machines. For example Docker lives within a VPS/host/machine, rather than a network, which the VPS/host/machine lives in.

Ex: Firewalls can be network based or VPS/host based
With IDS, IPS you have:
NIDS, NIPS for Network
HIDS, HIPS for VPS/Host

If the sections stay small, then there may not be to much of a problem, but if it grows, you will probably want to tease the Network apart from VPS/host as they are in many cases exclusive.

**Comment by sbilly** [comment]
Yes, I think so.
