### ISSUE TITLE
[IDEA] Add the Amass subdomain enumeration tool

### ISSUE THREAD

**Issue by caffix** [sbilly/awesome-security#91]
Amass is the most In-depth subdomain enumeration tool and performs DNS OSINT. This could fall under 'Scanning / Pentesting' on your awesome list. The Amass project can be found using the link below:

https://github.com/caffix/amass

Thanks in advance!

**Comment by hackdefendr** [comment]
Create a pull request with your addition.

**Comment by caffix** [comment]
Will do!
